# ##################################################################################
#                                                                                  #
# __      ______ _____ _____   _____ _    _ ______  _____ _______                  #
# \ \    / / __ \_   _|  __ \ / ____| |  | |  ____|/ ____|__   __|                 #
#  \ \  / / |  | || | | |  | | |    | |__| | |__  | (___    | |                    #
#   \ \/ /| |  | || | | |  | | |    |  __  |  __|  \___ \   | |                    #
#    \  / | |__| || |_| |__| | |____| |  | | |____ ____) |  | |                    #
#     \/   \____/_____|_____/ \_____|_|  |_|______|_____/   |_|                    #
#                                                                                  #
# ##################################################################################

# Configuration file for Options
Options:

  # Debug option
  debug: false

  # Secret option
  secret: "SECRET HERE"

  # Locale option
  locale: "en_US"

  # WARNING: Only use this feature if you know what you're doing.
  #
  # In case of you having issues with voidchests being deleted upon a restart, increase the number by a bit.
  #
  # How many seconds should the plugin wait before loading data (voidchests, player related data, etc.)
  # This will allow worlds and other things to load before voidchest so that you can avoid issues such as voidchest
  # attempting to load voidchests in worlds that have yet to load.
  #
  # This should only be modified if servers are having issues with worlds loading after the voidchest plugin has loaded.
  # Recommended load-delay interval is any number from 1 to 10, the highest, the more time the data will delay to load.
  #
  # Any number that is < 1 will make the plugin instantly load data when the plugin enabled as well.
  # Is NOT RECOMMENDED to set this to < 2.
  load delay: 5

  # WARNING: Only use this feature if you fully understand the implications.
  # In VoidChest 6.0 and later, this setting controls the interval at which changes are batched and saved.
  # The value represents the time (in SECONDS) between automatic saves of player and voidchest data.
  # The primary benefit of batching saves is to reduce performance overhead by saving changes less frequently,
  # rather than saving each change individually.
  #
  # However, please note: If the server crashes before changes are saved, you may lose unsaved data.
  #
  # The reason for introducing this feature is that, in previous versions, concurrent saves to the disk could occur
  # if one save operation was in progress while another change was made.
  # This could lead to file corruption, as two threads would be attempting to write to the same file simultaneously.
  #
  # Recommended Usage:
  # - Set a reasonable save interval to balance between performance and data safety.
  # - If you're running a highly active server with frequent changes, consider a lower save interval to reduce data loss risk.
  save interval: 20  # Time in SECONDS between saves. Adjust based on server load and performance needs.

  # Experimental features option
  experimental features: false

  # Metrics option
  metrics: true

  # Discord option
  discord: false

  # Updater option
  updater:
    enabled: true

  # VoidChest command option
  commands:
    voidchest: true
    voidchest admin: true

  database:
    type: "File" #Types File, SQLite, MySQL, MongoDB

    # SQL database options
    SQL:
      host: "localhost"     # SQL database host
      port: 3306            # SQL database port
      user: "youruser"      # SQL database username
      password: "yourpassword"   # SQL database password
      database: "VoidChest"   # SQL database name
      users table name: "voidchest_users"   # SQL table for users
      voidchests table name: "voidchest_voidchests"   # SQL table for voidchests
      SQLite file name: "voidchest"   # SQLite file name

    # MongoDB options
    MongoDB:
      host: "localhost"     # MongoDB host
      port: 27017           # MongoDB port
      user: "youruser"      # MongoDB username
      password: "yourpassword"   # MongoDB password
      database: "voidchest"   # MongoDB database name
      users collection: "voidchest_users"   # MongoDB collection for users
      voidchest collection: "voidchest_voidchests"   # MongoDB collection for voidchests

  # Certain timings are automatically converted into d,h,m,s.
  # For example, charge time, hologram sell interval, etc.
  # By changing these, you can modify the text to your liking.
  time format:
    second: second
    seconds: seconds
    minute: minute
    minutes: minutes
    hour: hour
    hours: hours
    day: day
    days: days
    invalid: Invalid

  money format: "##.####"

  # Available plugins: voidchest:vault, voidchest:the_new_economy, voidchest:voidchest, namespace:key (custom implementations)
  #
  # VoidChest built in economy only supports EXP levels for charge upgrades and payouts.
  economy:
    charge: "voidchest:vault"
    upgrades: "voidchest:vault"
    payout: "voidchest:vault"

  # Available modes: EXP and LEVELS
  void chest economy mode: "EXP"

  # Should the plugin attempt to hook to one of the Stacker plugins:
  # - voidchest:none
  # - voidchest:wildstacker
  # - voidchest:ultimatestacker
  # - voidchest:spacestacker
  # - voidchest:rosestacker
  # - voidchest:zitemstacker
  # - voidchest:cloudspawners
  # Developers can register their own using the API (Registry.STACKER) and then adding their namespaced key here
  stacker: "voidchest:none"

  # Should the plugin attempt to hook to one of the Bank plugins:
  # - voidchest:none
  # - voidchest:factions (all major faction plugins thanks to FactionsBridge)
  # - voidchest:royale_economy
  # - voidchest:superior_skyblock2
  # - voidchest:fabled_skyblock
  # - voidchest:mysql_economy_bank
  # Developers can register their own using the API (Registry.BANK) and then adding their namespaced key here
  bank: "voidchest:none"

  # Should the plugin attempt to hook to one of the Bank TNT plugins:
  # - voidchest:none
  # - voidchest:factions (all major faction plugins thanks to FactionsBridge)
  # Developers can register their own using the API (Registry.BANK_TNT) and then adding their namespaced key here
  bank tnt: "voidchest:none"

  # Available hologram support from other plugins: None, HolographicDisplays, Holograms, CMI, DecentHolograms, FancyHolograms.
  hologram:
    plugin: "None"
    # This value is in seconds.
    update interval: 1


  # Ignore item meta option
  ignore item meta: true

  # Set filter mode
  # Available modes: ALLOW and BLOCK
  # ALLOW: Only the items that match the filter are allowed to be sold/collected
  # BLOCK: Items that match the filter are blocked
  filter mode: "ALLOW"

  # Chunk see options
  chunk see:
    Y central: 0
    Y up: 0
    Y down: 0
    effect:
      type: "VILLAGER_HAPPY"
      interval: 20

  # Display sell message in the chat
  sell message:
    enabled: false
    # This value is in seconds.
    interval: 60

    # Should a sell message be sent when a player joins the server?
    offline:
      enabled: false
      message delay: 50
